name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - name: Prepare for Netlify Deployment
      uses: borales/actions-yarn@v2.0.0
      with:
          cmd: rw deploy netlify

    - name: Publish
      uses: netlify/actions/cli@master
      with:
        args: deploy --prod
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}