name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install -g yarn
    - run: yarn
    - run: npm install netlify-cli -g
    - run: netlify deploy --prod
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
